### ISSUE TITLE
Set Up Feature Branch Deployment

### ISSUE THREAD

**Issue by kornel-filep** [Idea-Pool/js-assertion-cheat-sheet#7]
Configure additional pipelines for feature branches. Feature branches match with the regex "[0-9]+-**" (Github Issue regex). This pipeline should be manual trigger only and should not be activated for the main branch.

Once a feature branch has been initially deployed, the URL established should remain constant. Along with this, we need to set up a separate pipeline for AWS CDK Stack cleanup, enabling us to tidy up the environment when necessary (destroy the whole stack).

Acceptance Criteria:
1. Github Actions pipeline is in place for feature branch deployments to AWS.
2. The pipeline should only trigger manually (workflow dispatch) for branches matching the "[0-9]+-**" regex.
3. It should not be available for the main branch.
4. The URL for a deployed feature branch remains constant after its first deployment.
5. Updates to a feature branch and manual deployment only change the website content, not the URL (after first deployment).
6. A second pipeline is available for complete AWS CDK Stack cleanup.

**Comment by kyouka5** [comment]
After pushing two pipelines to my branch, I have just noticed that I am not able to trigger them under the Actions tab. I did some digging, and found that pipelines with `workflow_dispatch` trigger can not be triggered as long as they are not in the main branch:

> To trigger the `workflow_dispatch` event, your workflow must be in the default branch. For more information about configuring the `workflow_dispatch` event, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)."

[Source](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow)

A solution for this problem could be to change the trigger in the pipelines to `push` while we are still testing our changes, and then before opening a PR we could update the trigger to be `workflow_dispatch`.

@kornel-filep What do you think, maybe do you have any better ideas in mind?

FYI @t0mmili @taughty

**Comment by kornel-filep** [comment]
> @kornel-filep What do you think, maybe do you have any better ideas in mind?

Sure that works for me @kyouka5.

**Comment by kornel-filep** [comment]
@t0mmili please check the above message from @kyouka5 as it potentially has impact to the main branch pipelines.

The idea is that the main brach will be deployed on `BASE_URL/` and the feature branches will be on `BASE_URL/BRANCH/` endpoints. This potentially has implications on how the feature and main branch pipelines work in tandem.
